### PR TITLE
Only use activate if dropdownLabel is passed too

### PR DESCRIPTION
**Pull request by shalecraig**
See https://github.com/julienXX/terminal-notifier/issues/223#issuecomment-305415020 for a lot more context

#### Disclaimers

* I don't really write/know objective-c
* I couldn't figure out the difference between `options` and `defaults`

### CODE REVIEW

**Comment by julienXX** [comment]
Thanks for the PR, I'll try to have a look quickly.

**Comment by shalecraig** [comment]
friendly bump 😄

**Comment by julienXX** [comment]
@shalecraig sorry while reviewing and testing your changes, I think I found another issue. I've got to do some more testing of the whole stuff sadly I don't have much time these days but I'll manage do do it somehow.

**Comment by shalecraig** [comment]
No worries. Figured I'd bump after a while.

Thanks for maintaining this awesome piece of Software. :)

**Comment by julienXX** [comment]
Closing for now. Version 2.0.0 as been released with alerter features removed https://github.com/julienXX/terminal-notifier/releases/tag/2.0.0

**Pull request closed without merging**
