### PR TITLE
Add a sound option

### PR DESCRIPTION
**Pull request by DidierA**
This modifications adds an optional -sound argument, allowing the user to add a sound to a notification.

### CODE REVIEW

**Comment by songpeng** [comment]
Hi, how can I close the sound or with limited volume for the sounds....

**Comment by lonnylundsten** [comment]
Would it be possible to add on option for playing the sound x number of times?
terminal-notifier -message TEST -sound Funky -repeat_sound 6

**Comment by julienXX** [comment]
I'll look into this but in the meantime you could make a new sound file made of x times the sound you need :)

**Comment by lonnylundsten** [comment]
Yes, true. I'll try that for now. Thank you.

**Pull request merged**
