### PR TITLE
Support reply

### PR DESCRIPTION
**Pull request by CharlieHess**
This PR adds support for [`NSUserNotification.hasReplyButton`](https://developer.apple.com/library/mac/documentation/Foundation/Reference/NSUserNotification_Class/index.html#//apple_ref/occ/instp/NSUserNotification/hasReplyButton) and listens for activations of type `NSUserNotificationActivationTypeReplied`. It is adapted from @vjeantet's [alerter](https://github.com/vjeantet/alerter).

The biggest change is that we can no longer exit immediately after a notification is delivered; we need to wait for `didActivateNotification` to retrieve the response value. In light of that I've also added support for timeouts à la https://github.com/julienXX/terminal-notifier/pull/109 (cc @mikaelbr). For backwards compatibility, if `reply` or `timeout` is not specified, the notifier will retain its original behavior of exiting immediately.

### CODE REVIEW

**Comment by CarlAndersson** [comment]
This would be great! It would give one very useful option to enable more user interactivity.

**Comment by julienXX** [comment]
Sorry Github sucks at notifications, I only see your PR now. I'll have a look and keep you posted. Thanks!

**Comment by mikaelbr** [comment]
This would be cool! 👍  There could also be different button types to support also?

**Comment by julienXX** [comment]
@CharlieHess I've seen with @vjeantet and we decided it would be great to directly merge alerter's feature directly in terminal-notifier. So thanks for your PR but I've merged alerter's code directly.

**Comment by julienXX** [comment]
@mikaelbr you can customize the buttons label or add a dropdown and with JSON output the sky is the limit :)

**Comment by Riokai** [comment]
@CharlieHess If you put a timeout and this will fire while the user is replying, the text he submitted won't be available.

**Pull request closed without merging**
