### PR TITLE
Adds feature for checking if user has clicked or on timeout

### PR DESCRIPTION
**Pull request by mikaelbr**
Hi and thanks for a great app!

I think it would be nice to have a feature where you can define whether or not to wait for user input and return a message if the user activated the notification (clicked) or it timed out. 

I hadn't looked at `NSUserNotificationCenter` before, or really programmed in ObjC, so this might be the wrong approach, but I didn't find any way of listening for when the notification ended (timed out). The rather naïve strategy of having a `dispatch_after` with a timeout of 6 seconds seemed like the best way.

The result of this is that you can do something like this:
```shell
➜  terminal-notifier.app  ./Contents/MacOS/terminal-notifier -message "foo"
➜  terminal-notifier.app  ./Contents/MacOS/terminal-notifier -message "foo" -wait YES
Activated
➜  terminal-notifier.app  ./Contents/MacOS/terminal-notifier -message "foo" -wait YES
Timeout
```

Where the `Activated` is printed when the notification bubble is clicked, or `Timeout` is printed after 6 seconds

Any thoughts about this?

### CODE REVIEW

**Comment by 127001** [comment]
Me too, really would like to have the option to leave the notification open until the user interacts with it.

**Comment by julienXX** [comment]
@127001 you could switch terminal-notifier notification style in System Preferences http://cl.ly/image/1X1h0y1j1G0T to get this behaviour.

**Comment by kurisubrooks** [comment]
@julienXX What if we wanted to use terminal-notifier in a commercial program? Making every one of our users change this setting is impractical. I'd really appreciate this feature.

**Comment by julienXX** [comment]
You now have this feature in terminal-notifier 1.7.0 :)

**Pull request closed without merging**
